-- AlterTable
ALTER TABLE "Motor" ADD COLUMN "connectionType" TEXT;
ALTER TABLE "Motor" ADD COLUMN "current" TEXT;
ALTER TABLE "Motor" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "Motor" ADD COLUMN "isActive" BOOLEAN DEFAULT true;
ALTER TABLE "Motor" ADD COLUMN "lastService" DATETIME;
ALTER TABLE "Motor" ADD COLUMN "manufacturer" TEXT;
ALTER TABLE "Motor" ADD COLUMN "modelNo" TEXT;
ALTER TABLE "Motor" ADD COLUMN "nextService" DATETIME;
ALTER TABLE "Motor" ADD COLUMN "notes" TEXT;
ALTER TABLE "Motor" ADD COLUMN "phase" TEXT;
ALTER TABLE "Motor" ADD COLUMN "powerKW" REAL;
ALTER TABLE "Motor" ADD COLUMN "protection" TEXT;
ALTER TABLE "Motor" ADD COLUMN "qrCode" TEXT;
ALTER TABLE "Motor" ADD COLUMN "rpm" INTEGER;
ALTER TABLE "Motor" ADD COLUMN "tag" TEXT;
ALTER TABLE "Motor" ADD COLUMN "voltage" TEXT;
ALTER TABLE "Motor" ADD COLUMN "year" INTEGER;
